---
apiVersion: v1
data:
  autoscalegroups.yaml: |
    autoScaleGroups:
      - name: loadbalancer
        scaleUpThreshold: "memory=0.7,cpu=0.7"
        labelSelector: "nodeType=loadbalancer"
        metricSource:
          type: kubernetes
        provisioner:
          type: ranchernodepool
          rancherNodePoolNamePrefix: "loadbalancer"
      - name: application
        scaleUpThreshold: "memory=0.7,cpu=0.7"
        labelSelector: "nodeType=application"
        metricSource:
          type: kubernetes
        provisioner:
          type: ranchernodepool
          rancherNodePoolNamePrefix: "worker"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: auto-scale-groups
  namespace: node-auto-scaler
---